image: cirrusci/flutter:3.3.6

stages:
  - build
  - test

doctor:
  stage: build
  script:
    - flutter doctor

build:
  stage: build
  script:
    - flutter build appbundle

widget-test:
  stage: test
  script:
    - flutter test